using UnityEngine;

namespace Pcb
{
    /// <summary>A point the spark stops at. Its 3D look is generated by the Board.</summary>
    public class PcbNode : MonoBehaviour
    {
        public NodeType type = NodeType.Capacitor;
        [Tooltip("Side this node sits on. Ignored for vias, which go through the board.")]
        public PcbLayer layer = PcbLayer.Front;
        [Tooltip("Goal only: chip size in world units.")]
        public Vector2 chipSize = new Vector2(1f, 1.5f);

        public bool IsVia => type == NodeType.Via;
        public bool IsOnLayer(PcbLayer l) => IsVia || layer == l;
    }
}
